spring.application.name=SprintSight

spring.datasource.url=${DB_URL}
spring.datasource.password=9lI4ZTqzmYvj7l64bMdU7arK5xnjhW7o
spring.datasource.username=sprint_sight_db_brhh_user

spring.jpa.hibernate.ddl-auto=update

spring.profiles.active=${ACTIVE_PROFILES}

SprintSight.app.jwtSecret=Qjn-WvVwqSzJ0h7NR-n6QgkaphPVZ5VklYMSJKPZ2r0

logging.level.com.example.sprintsight=INFO

logging.level.org.springframework=WARN
logging.level.org.hibernate=WARN

logging.pattern.console=%d{HH:mm:ss} [%level] %logger{36} - %msg%n

sprintsight.refresh-token.cleanup-cron=0 0 3 * * *
