spring.application.name=SprintSight

spring.datasource.url=jdbc:postgresql://db.zqugqtcfedhdbinjnyth.supabase.co:5432/postgres
spring.datasource.password=${DB_PASSWORD}
spring.datasource.username=${DB_USERNAME}
