spring.application.name=SprintSight

spring.datasource.url=jdbc:postgresql://db.zqugqtcfedhdbinjnyth.supabase.co:5432/postgres?sslmode=disable&connectTimeout=30
spring.datasource.password=_k4b+WeDe/23SUp
spring.datasource.username=postgres
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.show-sql=true
server.port=${PORT:8080}
server.ssl.enabled=${SSL_ENABLED:false}
#server.ssl.key-store=classpath:keystore.p12
#server.ssl.key-store-password=isshin
#server.ssl.keyStoreType=PKCS12
#server.ssl.keyAlias=homosawy


#server.http.port=8079
spring.jpa.hibernate.ddl-auto=update