spring.jpa.hibernate.ddl-auto=create-drop
spring.jpa.show-sql=false

logging.level.com.example.sprintsight=INFO
logging.level.org.springframework=WARN
logging.level.org.hibernate=WARN
logging.level.org.hibernate.SQL=WARN

management.endpoints.web.exposure.include=
